// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeTodoController() (TodoController, error) {
	todoRepository, err := NewInMemoryTodoRepo()
	if err != nil {
		return TodoController{}, err
	}
	todoService := NewTodoService(todoRepository)
	todoController := NewTodoController(todoService)
	return todoController, nil
}
