// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/shusann01116/gosandbox/todo"
)

// Injectors from wire.go:

func InitializeTodoController() (todo.Controller, error) {
	repository, err := todo.NewInMemoryRepo()
	if err != nil {
		return todo.Controller{}, err
	}
	service := todo.NewService(repository)
	controller := todo.NewController(service)
	return controller, nil
}
