name: CI

on:
  pull_request:
    types: [opened, edited]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest
      - name: Lint
        run: |
          echo "${{ github.event.pull_request.title }}" | npx commitlint
